name: Build and test node-stream-trim
on: [push]
jobs:
  build-test-module:
    name: Build & Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 
        uses: actions/checkout@v3

      - name: Setup node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
      
      - name: CI setup
        run: npm ci

      - name: Lint
        run: npm run lint

      - name: Build
        run: npm run build
        
      - name: Test
        run: npm test